apiVersion: v1
kind: Namespace
metadata:
  name: gateway-resphdr-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: gateway-resphdr-example
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: gateway-resphdr-example
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hello-resphdr-gw
  namespace: gateway-resphdr-example
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: resphdr.127.0.0.1.nip.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-resphdr-route
  namespace: gateway-resphdr-example
spec:
  parentRefs:
    - name: hello-resphdr-gw
  hostnames:
    - resphdr.127.0.0.1.nip.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: X-Powered-By
                value: "GatewayAPI"
      backendRefs:
        - name: hello
          port: 80
