apiVersion: v1
kind: Namespace
metadata:
  name: gw-cross-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-cross-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: app-cross-ns
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: app-cross-ns
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
---
# ReferenceGrant allows an HTTPRoute in a different namespace to reference a Service here
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-httproute-to-service
  namespace: app-cross-ns
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gw-cross-ns
  to:
    - group: ""
      kind: Service
      name: hello
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hello-gw
  namespace: gw-cross-ns
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: crossns.127.0.0.1.nip.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-route
  namespace: gw-cross-ns
spec:
  parentRefs:
    - name: hello-gw
  hostnames:
    - crossns.127.0.0.1.nip.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hello
          namespace: app-cross-ns
          port: 80
